name: bitaps_vpn
description: bitaps VPN — единый клиент на все ОС (iOS/Android/macOS/Windows/Linux)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  window_manager: ^0.3.7
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  http: ^1.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/gear.png
    - assets/gearring.png
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono.ttf

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  min_sdk_android: 24
  adaptive_icon_background: "#0C0A14"
  adaptive_icon_foreground: "assets/icon_fg.png"
  macos:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256
